# Generated by Django 4.2.6 on 2023-11-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_quizscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizscore',
            name='percentage_score',
            field=models.FloatField(null=True),
        ),
    ]
