# Generated by Django 5.1 on 2024-08-09 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_quizscore_percentage_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizscore',
            name='total_question',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
