# Generated by Django 5.1 on 2024-08-10 15:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_quizscore_total_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizscore',
            name='create_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name=django.utils.timezone.now),
        ),
    ]
